---
  - name: Configure Git global config
    blockinfile:
      marker: "# {mark} ANSIBLE MANAGED BLOCK - Configure Git"
      path: "{{ansible_env.HOME}}/.gitconfig"
      block: "{{ lookup('template', 'git_config') }}"
      create: yes
